export const imageArray = [
	require("./images/crossover.png"),
	require("./images/bike.png"),
	require("./images/supercar.png"),
	require("./images/jeep.png"),
	require("./images/hatchback.png"),
	require("./images/convertible.png"),
	require("./images/sedan.png"),
	require("./images/mustang.png"),
	require("./images/cooper.png"),
	require("./images/tractor.png"),
	require("./images/bicycle.png"),
	require("./images/truck.png"),
	require("./images/bus.png"),
	require("./images/loader.png"),
	require("./images/tank.png"),
	require("./images/helicopter.png"),
];
